### ISSUE TITLE
Will not compile with Xcode Version 16.2 (16C5032a)

### ISSUE THREAD

**Issue by ayrtonsoftware** [objectbox/objectbox-swift#89]
### Is there an existing issue?

- [ ] I have searched [existing issues](https://github.com/objectbox/objectbox-swift/issues)

### Build info

- ObjectBox version: [e.g. 1.9.0]
- OS: [e.g. iOS 17 | macOS 10.14 ]
- Device/chipset: [e.g. iPhone 15 | Apple M2 ]

### Steps to reproduce

_TODO Tell us exactly how to reproduce the problem._

Compile errors in example project:

/Users/fred/Projects/objectbox-swift-4.0.1/Example/Shared/Author.swift:10:16: error: type 'Note' does not conform to protocol 'EntityInspectable'
    var notes: ToMany<Note>
               ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/Services.swift:9:20: error: type 'Author' does not conform to protocol 'EntityInspectable'
    let authorBox: Box<Author>
                   ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/NoteEditingViewController.swift:168:25: error: type 'Author' does not conform to protocol 'EntityInspectable'
        init(authorBox: Box<Author>) {
                        ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/NoteEditingViewController.swift:46:18: error: type 'Note' does not conform to protocol 'EntityInspectable'
    var noteBox: Box<Note> = Services.instance.noteBox
                 ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/AuthorsOverviewViewController.swift:13:20: error: type 'Author' does not conform to protocol 'EntityInspectable'
    var authorBox: Box<Author> = Services.instance.authorBox
                   ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/MasterViewController.swift:8:23: error: type 'Note' does not conform to protocol 'EntityInspectable'
    lazy var noteBox: Box<Note> = Services.instance.noteBox
                      ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/MasterViewController.swift:10:25: error: type 'Author' does not conform to protocol 'EntityInspectable'
    lazy var authorBox: Box<Author> = Services.instance.authorBox
                        ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/AuthorEditingViewController.swift:8:20: error: type 'Author' does not conform to protocol 'EntityInspectable'
    var authorBox: Box<Author> = Services.instance.authorBox
                   ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/NotesOverviewViewController.swift:13:18: error: type 'Note' does not conform to protocol 'EntityInspectable'
    var noteBox: Box<Note> = Services.instance.noteBox
                 ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/NotesOverviewViewController.swift:20:20: error: type 'Note' does not conform to protocol 'EntityInspectable'
        let query: Query<Note>
                   ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/NotesOverviewViewController.swift:23:38: error: type 'Note' does not conform to protocol 'EntityInspectable'
        init(authorId: Id?, noteBox: Box<Note> = Services.instance.noteBox) {
                                     ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/NotesExample-iOS/Services.swift:10:18: error: type 'Note' does not conform to protocol 'EntityInspectable'
    let noteBox: Box<Note>
                 ^
/Users/fred/Projects/objectbox-swift-4.0.1/Example/Shared/Note.swift:20:17: error: type 'Author' does not conform to protocol 'EntityInspectable'
    var author: ToOne<Author> = nil

### Expected behavior

_TODO Tell us what you expect to happen._

### Actual behavior

_TODO Tell us what actually happens._

### Code

_TODO Add a code example to help us reproduce your problem._

<details><summary>Code</summary>

```swift
[Paste your code here]
```

</details>

### Logs, stack traces

_TODO Add relevant logs, a stack trace or crash report._

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ayrtonsoftware** [comment]
MacBook Pro Nov 2023 / Apple M3 Pro Memory: 16GB --- Sequoia 15.2

**Comment by greenrobot-team** [comment]
Did you run the code generator? See https://swift.objectbox.io/getting-started#generate-objectbox-code

Note: I labeled this issue with "more info required" so it will auto-close in a few days if there are no follow-up comments.
