### ISSUE TITLE
Crash at launch after upgrading to 1.4

### ISSUE THREAD

**Issue by thanhhai08sk** [objectbox/objectbox-swift#45]
**Describe the bug**
I was using 1.3.1 but then encounter the issue ["Could not open env for DB (12)"](https://github.com/objectbox/objectbox-swift/issues/25). I try to upgrade to 1.4.1 and 1.4.0 but the app crash at launch with:

```dyld: symbol '_$s9ObjectBox13EntityBindingP09generatorD7VersionSiyFTq' not found, expected in '/private/var/containers/Bundle/Application/4D3A6114-9D36-4C10-856E-9FD825083863/Journal it!.app/Frameworks/ObjectBox.framework/ObjectBox', needed by '/private/var/containers/Bundle/Application/4D3A6114-9D36-4C10-856E-9FD825083863/Journal it!.app/Frameworks/CoreIOS.framework/CoreIOS'```

ObjectBox is used in the common module CoreIOS. The generator script seems to work:
`"$PODS_ROOT/ObjectBox/generate_sources.sh" -- --output "$PROJECT_DIR/generated/EntityInfo-CoreIOS.generated.swift" --model-json "$PROJECT_DIR/model-CoreIOS.json" # add this parameter to make entities exportable: --visibility public
`

**Basic info (please complete the following information):**
 - ObjectBox version 1.4.1/1.4.0
 - Reproducibility: always
 - Device: iPhone 6s
 - OS:  iOS 14.2

**To Reproduce**
1. Upgrade Objectbox following https://swift.objectbox.io/install
2. Build
3. Crash at launch

**Comment by greenrobot** [comment]
> Upgrade Objectbox following https://swift.objectbox.io/install

So, you did the following?

```
pod repo update
pod update ObjectBox
Pods/ObjectBox/setup.rb
```

Can you paste the output of running setup.rb, please?

**Comment by thanhhai08sk** [comment]
Yes, I did.
The output:
```
MacBook-Pro:CoreIOS HaiNguyen$ Pods/ObjectBox/setup.rb
 ObjectBox Project Setup 

🔸 Looking for project files in the current directory ...
🔸 Found a single project.
🔸 Using "/Users/HaiNguyen/Documents/githubProject/JournalIt/journal_it/ios/CoreIOS/CoreIOS.xcodeproj"
🛑 No launchable Xcode targets found in "/Users/HaiNguyen/Documents/githubProject/JournalIt/journal_it/ios/CoreIOS/CoreIOS.xcodeproj"
ℹ️ Please specify project and target explicitly; run with --help for help

```
Not sure if there's anything wrong but CoreIOS is a framework module, EntityInfo-CoreIOS.generated.swift was refreshed on each build, and I didn't have problem with version 1.3.1

**Comment by greenrobot** [comment]
Can you please try what is suggested here: `# add this parameter to make entities exportable: --visibility public`

To do this you have to locate the script in the Xcode build phase "[OBX] Update Sourcery Generated Files".

It might also be helpful to check the following docs: [manual-installation](https://swift.objectbox.io/advanced/manual-installation), [setup-script](https://swift.objectbox.io/advanced/setup-script), and [code generation](https://swift.objectbox.io/advanced/sourcery).

Once we know what exactly is going on we'll try to make it simpler in the future. E.g. looking at [setup.rb](https://github.com/objectbox/objectbox-swift/blob/5006055af619f9a5107ad6be2fa1554b43730387/Source/ios-framework/cocoapod/setup.rb#L264-L266):

```
  if !target.launchable_target_type? # probably a framework. Add a common use case reminder.
      obx_shell_script << " # add this parameter to make entities exportable: --visibility public"
  end
```

It might be better to detect a framework reliably, but not sure how exactly that could be done yet with what [xcodeproj has to offer](https://rubydoc.info/gems/xcodeproj/Xcodeproj/Project/Object/PBXNativeTarget).

**Comment by thanhhai08sk** [comment]
Unfortunately, I tried to add ` --visibility public` but got the same result.

Checked the docs, though I can't find anything to try out for this problem.

**Comment by greenrobot-team** [comment]
This appears to be an issue with the setup.rb script. Without having access to the Xcode project can not reproduce.

So closing this issue due to inactivity. :zzz: Feel free to comment with more details or submit a new issue.
